/*
 * Created on 29 thg 9 2017 ( Time 12:01:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.dream_reader.bean.Contents;
import org.dream_reader.bean.jpa.ContentsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ContentsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ContentsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ContentsEntity' to 'Contents'
	 * @param contentsEntity
	 */
	public Contents mapContentsEntityToContents(ContentsEntity contentsEntity) {
		if(contentsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Contents contents = map(contentsEntity, Contents.class);

		return contents;
	}
	
	/**
	 * Mapping from 'Contents' to 'ContentsEntity'
	 * @param contents
	 * @param contentsEntity
	 */
	public void mapContentsToContentsEntity(Contents contents, ContentsEntity contentsEntity) {
		if(contents == null) {
			return;
		}

		//--- Generic mapping 
		map(contents, contentsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}