/*
 * Created on 2 thg 10 2017 ( Time 16:45:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.dream_reader.bean.PaymentHistory;
import org.dream_reader.bean.jpa.PaymentHistoryEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PaymentHistoryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PaymentHistoryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PaymentHistoryEntity' to 'PaymentHistory'
	 * @param paymentHistoryEntity
	 */
	public PaymentHistory mapPaymentHistoryEntityToPaymentHistory(PaymentHistoryEntity paymentHistoryEntity) {
		if(paymentHistoryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PaymentHistory paymentHistory = map(paymentHistoryEntity, PaymentHistory.class);

		return paymentHistory;
	}
	
	/**
	 * Mapping from 'PaymentHistory' to 'PaymentHistoryEntity'
	 * @param paymentHistory
	 * @param paymentHistoryEntity
	 */
	public void mapPaymentHistoryToPaymentHistoryEntity(PaymentHistory paymentHistory, PaymentHistoryEntity paymentHistoryEntity) {
		if(paymentHistory == null) {
			return;
		}

		//--- Generic mapping 
		map(paymentHistory, paymentHistoryEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}