/*
 * Created on 29 thg 9 2017 ( Time 12:01:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.business.service;

import java.util.List;
import java.util.Map;
import org.dream_reader.bean.jpa.ContentsEntity;
import org.dream_reader.bean.Contents;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Contents.
 */
public interface ContentsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Contents findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ContentsEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Contents> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ContentsEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Contents save(Contents entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Contents update(Contents entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Contents create(Contents entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<ContentsEntity> listPaging(Integer page,Integer size);

	Page<ContentsEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
	
	List<ContentsEntity> findByCategoryId(Integer categoryId);
}
