/*
 * Created on 2 thg 10 2017 ( Time 16:45:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.business.service;

import java.util.List;
import java.util.Map;
import org.dream_reader.bean.jpa.PaymentHistoryEntity;
import org.dream_reader.bean.PaymentHistory;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity PaymentHistory.
 */
public interface PaymentHistoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	PaymentHistory findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	PaymentHistoryEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<PaymentHistory> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<PaymentHistoryEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PaymentHistory save(PaymentHistory entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PaymentHistory update(PaymentHistory entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PaymentHistory create(PaymentHistory entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<PaymentHistoryEntity> listPaging(Integer page,Integer size);
	
	Page<PaymentHistoryEntity> listPagingByUserId( Integer page, Integer size, Integer userId);



	Page<PaymentHistoryEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
}
