/*
 * Created on 27 thg 9 2017 ( Time 14:44:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.web.common;

import java.util.Date;
import java.util.Iterator;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.dream_reader.bean.UserItem;
import org.dream_reader.business.service.UserService;
import org.dream_reader.web.common.Login;

public abstract class AbstractController {
	@Resource
	private UserService userService;

	@Autowired
	private HttpServletRequest request;
	@Autowired
	private HttpSession session;

	protected String getView() {
		return request.getRequestURI();
	}

	protected String redirectView() {
		return "redirect:"+request.getRequestURI();
	}
	
	@ModelAttribute(value="userPoint")
	protected Integer userPoint() {
		try {
			UserItem u = Login.getUserLogin(session);
			return u.getPoint();
		} catch (Exception e) {
			return 0;
		}
	
	}
	
	protected String redirectList() {
		String uri = request.getRequestURI();
		Integer index = uri.lastIndexOf("/");
		return "redirect:"+uri.substring(0, index)+"/list";
	}

	@ModelAttribute(value = "user")
	protected UserItem getUser() {
		return Login.getUserLogin(request.getSession(true));
	}
	
	@ModelAttribute(value = "admin")
	protected UserItem getAdmin() {
		return Login.getAdminLogin(request.getSession(true));
	}

	protected ResponseEntity<?> SUCCESS() {
		return new ResponseEntity<>(HttpStatus.OK);
	}

	protected ResponseEntity<?> SUCCESS(Object data) {
		return new ResponseEntity<>(data, HttpStatus.OK);
	}

	protected ResponseEntity<?> FAIL(Object data) {
		return new ResponseEntity<>(data, HttpStatus.BAD_REQUEST);
	}

	protected ResponseEntity<?> ERROR() {
		return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
	}
	
	

}