/*
 * Created on 3 thg 10 2017 ( Time 15:15:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class PaymentHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer userId;


    private Integer money;


    private Integer point;

    @NotNull
    private Short status;

    @Size( max = 50 )
    private String paymentMethod;

    @Size( max = 500 )
    private String tid;

    @Size( max = 50 )
    private String reason;

    @Size( max = 65535 )
    private String accountInfo;

    @NotNull
    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setMoney( Integer money ) {
        this.money = money;
    }
    public Integer getMoney() {
        return this.money;
    }

    public void setPoint( Integer point ) {
        this.point = point;
    }
    public Integer getPoint() {
        return this.point;
    }

    public void setStatus( Short status ) {
        this.status = status;
    }
    public Short getStatus() {
        return this.status;
    }

    public void setPaymentMethod( String paymentMethod ) {
        this.paymentMethod = paymentMethod;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    public void setTid( String tid ) {
        this.tid = tid;
    }
    public String getTid() {
        return this.tid;
    }

    public void setReason( String reason ) {
        this.reason = reason;
    }
    public String getReason() {
        return this.reason;
    }

    public void setAccountInfo( String accountInfo ) {
        this.accountInfo = accountInfo;
    }
    public String getAccountInfo() {
        return this.accountInfo;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(money);
        sb.append("|");
        sb.append(point);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(paymentMethod);
        sb.append("|");
        sb.append(tid);
        sb.append("|");
        sb.append(reason);
        // attribute 'accountInfo' not usable (type = String Long Text)
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
