/*
 * Created on 29 thg 9 2017 ( Time 12:01:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.dream_reader.business.service.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.annotation.Resource;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import org.springframework.data.jpa.domain.Specification;

import org.dream_reader.bean.Category;
import org.dream_reader.bean.jpa.CategoryEntity;
import org.dream_reader.business.service.CategoryService;
import org.dream_reader.business.service.mapping.CategoryServiceMapper;
import org.dream_reader.data.repository.jpa.CategoryJpaRepository;
import org.dream_reader.web.common.utils.DataUtils;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.domain.Sort.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
/**
 * Implementation of CategoryService
 */
@Component
@Transactional
public class CategoryServiceImpl implements CategoryService {

	@Resource
	private CategoryJpaRepository categoryJpaRepository;

	private static final Integer PAGE_SIZE   = 15;

	@Resource
	private CategoryServiceMapper categoryServiceMapper;
	
	@Override
	public Category findById(Integer id) {
		CategoryEntity categoryEntity = categoryJpaRepository.findOne(id);
		return categoryServiceMapper.mapCategoryEntityToCategory(categoryEntity);
	}

	@Override
	public CategoryEntity findOne(Integer id) {
		CategoryEntity categoryEntity = categoryJpaRepository.findOne(id);
		return categoryEntity;
	}

	@Override
	public Page<CategoryEntity> findAll(Integer pageNumber) {

		PageRequest request = new PageRequest(pageNumber - 1, PAGE_SIZE,
				new Sort(new Order(Direction.DESC, "id")));
		return categoryJpaRepository.findAll(request);
	}

	@Override
	public List<Category> findAll() {
		Iterable<CategoryEntity> entities = categoryJpaRepository.findAll();
		List<Category> beans = new ArrayList<Category>();
		for(CategoryEntity categoryEntity : entities) {
			beans.add(categoryServiceMapper.mapCategoryEntityToCategory(categoryEntity));
		}
		return beans;
	}

	/**
	 * Count total entit
	 * @return Long
	 */
	public Long countTotal(){
		Long count = categoryJpaRepository.count();
		return count;
	}

	@Override
	public Category save(Category category) {
		return update(category) ;
	}

	@Override
	public Category create(Category category) {
/*
		CategoryEntity categoryEntity = categoryJpaRepository.findOne(category.getId());
		if( categoryEntity != null ) {
			throw new IllegalStateException("already.exists");
		}

		categoryEntity = new CategoryEntity();
		categoryServiceMapper.mapCategoryToCategoryEntity(category, categoryEntity);
		CategoryEntity categoryEntitySaved = categoryJpaRepository.save(categoryEntity);
		return categoryServiceMapper.mapCategoryEntityToCategory(categoryEntitySaved);
*/
		CategoryEntity categoryEntity = new CategoryEntity();
		categoryServiceMapper.mapCategoryToCategoryEntity(category, categoryEntity);
		CategoryEntity categoryEntitySaved = categoryJpaRepository.save(categoryEntity);
		return categoryServiceMapper.mapCategoryEntityToCategory(categoryEntitySaved);
	}

	@Override
	public Category update(Category category) {
		CategoryEntity categoryEntity = categoryJpaRepository.findOne(category.getId());
		categoryServiceMapper.mapCategoryToCategoryEntity(category, categoryEntity);
		CategoryEntity categoryEntitySaved = categoryJpaRepository.save(categoryEntity);
		return categoryServiceMapper.mapCategoryEntityToCategory(categoryEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		categoryJpaRepository.delete(id);
	}

	public CategoryJpaRepository getCategoryJpaRepository() {
		return categoryJpaRepository;
	}

	public void setCategoryJpaRepository(CategoryJpaRepository categoryJpaRepository) {
		this.categoryJpaRepository = categoryJpaRepository;
	}

	public CategoryServiceMapper getCategoryServiceMapper() {
		return categoryServiceMapper;
	}

	public void setCategoryServiceMapper(CategoryServiceMapper categoryServiceMapper) {
		this.categoryServiceMapper = categoryServiceMapper;
	}

	@Override
	public Page<CategoryEntity> listPaging(Integer page, Integer size) {
		try {
			PageRequest pageable = new PageRequest(page-1, size, new Sort(new Order(Direction.DESC, "createDate")));
			return categoryJpaRepository.listPaging(pageable);
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}
	
	



	@Override
	public Page<CategoryEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size) {

		Specification<CategoryEntity> spec = new Specification<CategoryEntity>() {
			@Override
			public Predicate toPredicate(Root<CategoryEntity> root, CriteriaQuery<?> query, CriteriaBuilder cb) {
				List<Predicate> predicates = new ArrayList<>();

				if (params.get("key") != null) {
				String key = String.valueOf(params.get("key"));
					if (params.get("type") != null) {
						String type = String.valueOf(params.get("type"));
						Predicate predicate = cb.equal(root.get(type), "%"+key+"%");
						predicates.add(predicate);
					}
				}

				return cb.and(predicates.toArray(new Predicate[] {}));
			}

		};

		Order order = new Order(Direction.DESC, "createDate");
		if (params.get("orderBy") != null) {
			String orderBy = String.valueOf(params.get("orderBy"));
			order = new Order(Direction.DESC, orderBy);
		}

		PageRequest pageable = new PageRequest(page - 1, size, new Sort(order));
		return categoryJpaRepository.findAll(spec, pageable);
	}

	@Override
	public List<CategoryEntity> findByParentId(Integer parentId) {
		try {
			return categoryJpaRepository.findByParentId(parentId);
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

}
